### ISSUE TITLE
Ao keeps on getting logged out

### ISSUE THREAD

**Issue by Slater91** [825i/ao#20] opened 2021-01-20 20:10 UTC
**Describe the bug**
Ao seems to suffer from some issue that prevents it from keeping the user logged in.

**To Reproduce**
Log in and wait for a few hours. A warning message appear that the page needs to be refreshed. Click on it.
Alternatively, open ao.

**Expected behavior**
The account stays logged in even after the refresh or after being closed and re-opened.

**Technical Info (please complete the following information)**
 - OS: KDE neon (based on Ubuntu Focal)
 - Ao Version: 7.0.0

**Comment by pythonInRelay** [comment] 2021-08-04 08:41
I have not experienced this issue at all. I think it is something on your end. Still using this to date. You could be logged out when accessing the service from another address or changing IP address/using a VPN. This is normal. For now I am closing because I cannot replicate the issue.

**Comment by Slater91** [comment] 2021-08-04 10:07
While I don't dispute that you can't replicate it, I've tried multiple things:
- removing ao and its associated data and then re-installing it;
- trying it on an another computer;
- look at logs.
Nothing appeared to work. I have a fixed IP address and I don't use a VPN. While it's still possible that the issue is indeed on my end, everything seems to point to an issue with Ao.

**Comment by chekoopa** [comment] 2021-08-04 11:22
> While I don't dispute that you can't replicate it, I've tried multiple things:

Try also just using it from your browser. It could be account issue, too. I don't have such an issue either.

**Comment by Slater91** [comment] 2021-08-04 11:27
> Try also just using it from your browser. It could be account issue, too. I don't have such an issue either.

I have no issues using To Do from the browser.
Anyway, due to this issue I moved to Zenkit To Do in the meantime and I stopped using Ao, so this is not really relevant to me any more.

**Comment by pythonInRelay** [comment] 2021-08-06 10:55
Zenkit looks really nice, thanks for sharing. Unfortunately though the free plan is a little limited. Still an elegant alternative and reminds me of Wunderlist. I miss Wunderlist to be honest :/

**Comment by pythonInRelay** [comment] 2021-08-06 10:55
Mind you, I just rebuilt and released v 7.0 of ao. Maybe try that if you feel like it, perhaps the problem is solved.

**Comment by pythonInRelay** [comment] 2021-08-10 07:38
This is now happening for me after 7.0.1. Previous login information is cached, so it's only a single button click to login again, but nonetheless it shouldn't log the user out.

Need to investigate if this is due to an issue on M$' side or the app.

**Comment by Slater91** [comment] 2021-08-10 19:05
Yes, it seems like it's now better than it was (before it used to log out the user completely, so one had to do all the login process all over again each time), but it's still quite inconvenient.
I tried accessing the service from the browser but it does the same thing. I pinged them on Twitter but didn't get any reply. Let me know if you discover anything!

**Comment by chekoopa** [comment] 2021-08-11 02:07
> This is now happening for me after 7.0.1. Previous login information is cached, so it's only a single button click to login again, but nonetheless it shouldn't log the user out.

Oh, it's just like mine, and it had started even before 7.0.0, AFAIR. I just didn't complain because of previous login information. Sure it's on M$' side, as it behaves the same in my Chromium browser.

**Comment by pythonInRelay** [comment] 2021-08-11 06:54
I have noticed that I actually get this problem using other non-native apps on Linux. For example I am getting this via an electron mail client. Not fully logged out, but pushed back to one-click login page. I am pretty certain that this is something on M$' end and I don't really have the expertise to try and figure out what that is.

I'm also considering a complete rewrite of this app in Dart, but with a full-time job it's taking a bit of time.

**Comment by tareqimbasher** [comment] 2021-11-02 22:04
I also experience this. When I quit the app entirely and then reopen it, it asks me to login again. It doesn't log me out after extended standby, just when I quit the app and reopen it.

**Comment by pythonInRelay** [comment] 2021-11-02 22:12
Hi,

I no longer maintain this project on my own. I moved temporarily to Zenkit To-Do but that does not suit my needs. I recommend harassing Microsoft to make a native Linux version (or at least a better electron version), or trying another to-do list.

As my company also moved from Microsoft to Google, I personally hate Electron and this was not my project in the first place and the original author has never even once bothered to get back to me - there is absolutely no good reason for me to keep working on this project. I'll keep the repo up though of course, in case someone else wants to contribute to it.

**Closed** 2022-12-17 01:36 UTC
